---

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:

  - name: Delete old kernel from the hosts
    yum:
      name:
         - kernel-core-4.18.0-372.26.1.0.1.el8_6.x86_64
         - kernel-devel-4.18.0-372.26.1.0.1.el8_6.x86_64
         - kernel-modules-4.18.0-372.26.1.0.1.el8_6.x86_64
         - kernel-4.18.0-372.26.1.0.1.el8_6.x86_64
      state: absent
