---

- hosts: all
  become: true
  become_user: root
  tasks:

  - name: Update all Packages on yum based systems
    yum:
       name:
          - tcl
          - redis_exporter
       update_cache: true
       state: latest
    when: ansible_distribution in ["OracleLinux", "CentOS"]


  - name: Update all Packages on apt based systems
    apt:
       name: net-tools
       update_cache: true
       state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

