---
- hosts: all
  become: true
  tasks:
 
   - name: Add MongoDB Repository
     copy:
        src: /home/ansadm/Documents/Configs/mongodb-enterprise-5.0.repo
        dest: /etc/yum.repos.d/


   - name: Install MongoDB & mongodb_exporter
     yum:
       name: 
         - mongodb-enterprise
         - mongodb_exporter
       state: latest
