---

- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
  
  - name: Restart NTPD Service
    service:
       name: "{{ item }}"
       state: restarted
    with_items:
      - ntpd
